// <auto-generated />
using System;
using Doceria.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Doceria.Migrations
{
    [DbContext(typeof(DoceriaDbContext))]
    partial class DoceriaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Doceria.Models.Torta", b =>
            {
                b.Property<int>("TordaId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TordaId"));

                b.Property<DateTime>("Data")
                    .HasColumnType("datetime2")
                    .HasColumnName("DT_CADASTRO");

                b.Property<string>("Descricao")
                    .IsRequired()
                    .HasMaxLength(250)
                    .HasColumnType("nvarchar(250)")
                    .HasColumnName("DS_TORTA");

                b.Property<bool>("IsVegana")
                    .HasColumnType("bit")
                    .HasColumnName("BL_VEGANA");

                b.Property<string>("Nome")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)")
                    .HasColumnName("NM_TORTA");

                b.Property<decimal>("Preco")
                    .HasColumnType("decimal(18,2)")
                    .HasColumnName("VL_PRECO");

                b.Property<int>("Tipo")
                    .HasColumnType("int")
                    .HasColumnName("NM_TIPO");

                b.HasKey("TordaId");

                b.ToTable("TB_TORTA", (string)null);
            });
#pragma warning restore 612, 618
        }
    }
}